/* @ingroup     ashrait emv protocol implementation
 * @file        ashProtocol.cpp
 * @brief       implementation of ASHRAIT EMV v?????
 *
 *              This module reads the xml file generated by Ashrait
 *              and stores it for emvCard's use inside a binarySearchTree
 *
 ************************************************************************/

void CAT_main( void);
/**
 * @brief   Returns the terminal's address. There can be only one terminal
 *          using that address on the local network
 * @return  byte address
 */
//uint8_t CAT_getMyAddress(void);

